name = "lovense-cloud"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
LOVENSE_UID = "mai"

[[durable_objects.bindings]]
name = "LOVENSE_CLOUD"
class_name = "LovenseCloud"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LovenseCloud"]
